config/routes.rb
Rails.application.routes.draw do
  get 'gamememberships/create'

  get 'games/show'

  mount ActionCable.server => '/cable'

  
  #get '/games/new', to: 'games#new'
  #get '/games/:id', to: 'games#show'
  resources :games do
    post 'enroll' => 'gamememberships#create'
  end
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get 'logout' => 'sessions#destroy'
  post 'logout' => 'sessions#destroy'
  
  root :to => 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testgame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
    
    .header{
      height:50px;
      background:#8080F0;
      width: 100%;
      margin:0px;
      padding:0;
    }
    
    .header .blah{
      text-align:right;
    }
    
    .pokecard{
      height:150px;
      width:150px;
      border: 1px solid;
      background-color:white;
    }
    .pokecard.black{
      background-color:black;
    }
    .pokecard.red{
      background-color:red;
    }
    
    .pokecard.blue{
      background-color:blue;
    }
    
    .pokecard.gray{
      background-color:gray;
    }
    
    .mini-display{
      height:20px;
      width:20px;
      border: 0.5px solid;
      background-color:white;
    }
    .mini-display.black{
      background-color:black;
    }
    .mini-display.red{
      background-color:red;
    }
    .mini-display.blue{
      background-color:blue;
    }
    </style>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default">
      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <a href="#">
            <% if @current_user %>
              Hi <%= @current_user.username %></h3>
            <% else %>
            --> Pokemon codenames
            <% end %>
            </a>
          </li>
          <li>
            <%= link_to oinky_poo, logout_path %>
          </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>